// ============================================================
//  DATA.JS — Single source of truth
//  All project data + i18n translations
// ============================================================

const TRANSLATIONS = {
  fr: {
    nav: { skills: "Compétences", projects: "Projets", contact: "Contact" },
    hero: {
      tag: "Étudiant Bac Pro CIEL — Cybersécurité, Informatique, Réseau & Électronique",
      greeting: "Bonjour, je suis",
      name: "Victor Ponthus",
      sub: "Passionné par la cybersécurité, le développement logiciel et le hardware — je construis des projets concrets qui allient code, sécurité et curiosité technique.",
      cta_projects: "Voir mes projets",
      cta_contact: "Me contacter",
      scroll: "Scroll",
    },
    skills: {
      title: "Compétences",
      categories: [
        { name: "Développement", tags: ["Python","JavaScript","HTML / CSS","VBA","Next.js","Custom Tkinter"] },
        { name: "Cybersécurité",  tags: ["Pentesting","ESP32 / Firmware","Analyse réseau","Chiffrement","Wi-Fi & Bluetooth","OSINT"] },
        { name: "Systèmes & Outils", tags: ["Linux / Debian","Administration serveur","Hardware / Assemblage PC","Git / GitHub","Vercel","Microsoft Excel"] },
      ]
    },
    projects: { title: "Projets", details: "Voir les détails", github: "GitHub", demo: "Démo", close: "Fermer", features: "Fonctionnalités", tech: "Technologies", context: "Contexte" },
    contact: {
      title: "Contact",
      heading: "Travaillons ensemble",
      sub: "Tu as un projet en tête, une idée à développer, ou tu cherches un collaborateur ? Je suis disponible — envoie-moi un message.",
      name: "Nom", email: "Email", message: "Message",
      name_ph: "Ton nom", email_ph: "ton@email.com", msg_ph: "Décris ton projet...",
      send: "Envoyer le message",
      success: "✓ Message envoyé ! Je te réponds bientôt.",
      error: "Configure Formspree ou utilise le lien mail ci-dessous.",
    },
    about: {
      title: "À propos",
      lead: "Je suis Victor Ponthus, étudiant en Bac Pro CIEL à ma 3ème année. Passionné de tech, de cuisine et de cinéma — j'essaie de tout faire avec la même intensité.",
      sub: "J'ai pas mal voyagé aussi. Voici quelques pays où je suis allé :",
      cooking: {
        title: "La cuisine",
        desc: "Mon plat signature : poulet curry coco. Mais je maîtrise vraiment beaucoup de choses — de la carbonnade flamande au gratin dauphinois, en passant par de belles pièces de boeuf.",
      },
      cinema: {
        title: "Le cinéma",
        desc: "Plus de 100 films en 2024. Objectif 300 en 2025. J'ai vu toute la filmographie de Kubrick, courts-métrages inclus.",
        fav1: "The Shining — film préféré",
        fav2: "Eraserhead, Blue Velvet…",
      },
      sport: {
        title: "Sport & musculation",
        desc: "Hypertrophie, randonnée. Encore débutant mais ça progresse — les chiffres parlent d'eux-mêmes.",
      },
    },
    footer: { copy: "© 2025 Victor Ponthus — Tous droits réservés" },
    theme: { light: "Mode clair", dark: "Mode sombre" },
  },
  en: {
    nav: { skills: "Skills", projects: "Projects", contact: "Contact" },
    hero: {
      tag: "Bac Pro CIEL Student — Cybersecurity, Networks & Electronics",
      greeting: "Hi, I'm",
      name: "Victor Ponthus",
      sub: "Passionate about cybersecurity, software development and hardware — I build real-world projects combining code, security and technical curiosity.",
      cta_projects: "See my projects",
      cta_contact: "Get in touch",
      scroll: "Scroll",
    },
    skills: {
      title: "Skills",
      categories: [
        { name: "Development", tags: ["Python","JavaScript","HTML / CSS","VBA","Next.js","Custom Tkinter"] },
        { name: "Cybersecurity", tags: ["Pentesting","ESP32 / Firmware","Network Analysis","Encryption","Wi-Fi & Bluetooth","OSINT"] },
        { name: "Systems & Tools", tags: ["Linux / Debian","Server Administration","Hardware / PC Building","Git / GitHub","Vercel","Microsoft Excel"] },
      ]
    },
    projects: { title: "Projects", details: "See details", github: "GitHub", demo: "Demo", close: "Close", features: "Features", tech: "Technologies", context: "Context" },
    contact: {
      title: "Contact",
      heading: "Let's work together",
      sub: "Got a project in mind, an idea to develop, or looking for a collaborator? I'm available — send me a message.",
      name: "Name", email: "Email", message: "Message",
      name_ph: "Your name", email_ph: "you@email.com", msg_ph: "Describe your project...",
      send: "Send message",
      success: "✓ Message sent! I'll get back to you soon.",
      error: "Set up Formspree or use the email link below.",
    },
    about: {
      title: "About",
      lead: "I'm Victor Ponthus, a Bac Pro CIEL student in my 3rd year. Passionate about tech, cooking and cinema — I try to approach everything with the same intensity.",
      sub: "I've also traveled quite a bit. Here are some countries I've visited:",
      cooking: {
        title: "Cooking",
        desc: "My signature dish: coconut chicken curry. But I really master a wide range — from Flemish beef stew to gratin dauphinois, to beautiful cuts of beef.",
      },
      cinema: {
        title: "Cinema",
        desc: "Over 100 films in 2024. Target: 300 in 2025. I've seen Kubrick's entire filmography, including short films.",
        fav1: "The Shining — all-time favorite",
        fav2: "Eraserhead, Blue Velvet…",
      },
      sport: {
        title: "Sport & fitness",
        desc: "Hypertrophy training, hiking. Still a beginner but progressing — the numbers speak for themselves.",
      },
    },
    footer: { copy: "© 2025 Victor Ponthus — All rights reserved" },
    theme: { light: "Light mode", dark: "Dark mode" },
  }
};

const PROJECTS = [
  {
    id: "tool",
    num: "001",
    github: "https://github.com/VictorFrr/nextjs-portfolio-pageview-counter",
    demo: null,
    image: "images/tool.svg",
    color: "#00e5ff",
    fr: {
      title: "Tool de cybersécurité multifonctions",
      short: "Outil Python modulaire en interface console, inspiré de Mr. Robot. Projet majeur de fin de Bac Pro.",
      context: "Projet de fin de Bac Pro CIEL. Conçu comme une boîte à outils modulaire autour de la cybersécurité, l'analyse réseau et la sensibilisation aux bonnes pratiques. L'interface s'ouvre sur un logo ASCII eCorp, en référence à la série Mr. Robot.",
      features: [
        "Vérification de robustesse des mots de passe (CheckMdp)",
        "Générateur de mots de passe sécurisés",
        "Ping d'adresses IP & scan réseau",
        "IP lookup & test de vitesse réseau",
        "Modules de simulation de phishing (Facebook, Instagram, TikTok…)",
        "Quiz de cybersécurité & informatique générale",
        "Console interne & gestion de modules",
        "Module keylogger intégré (cadre pédagogique)",
      ],
      tech: ["Python", "CMD / Terminal", "Architecture modulaire", "Bibliothèques standard Python"],
    },
    en: {
      title: "Multi-function Cybersecurity Tool",
      short: "Modular Python tool with a console interface inspired by Mr. Robot. Main Bac Pro final project.",
      context: "Final project for Bac Pro CIEL. Designed as a modular toolbox around cybersecurity, network analysis and security awareness. The interface opens with an ASCII eCorp logo, referencing the Mr. Robot series.",
      features: [
        "Password strength checker (CheckMdp)",
        "Secure password generator",
        "IP ping & network scanner",
        "IP lookup & network speed test",
        "Phishing simulation modules (Facebook, Instagram, TikTok…)",
        "Cybersecurity & general IT quiz",
        "Internal console & module management",
        "Integrated keylogger module (educational context)",
      ],
      tech: ["Python", "CMD / Terminal", "Modular Architecture", "Python Standard Libraries"],
    }
  },
  {
    id: "esp32",
    num: "002",
    github: "https://github.com/VictorFrr",
    demo: null,
    image: "images/esp32.svg",
    color: "#7b61ff",
    fr: {
      title: "ESP32 Marauder — Pentesting Wi-Fi & Bluetooth",
      short: "ESP32 flashé avec le firmware Marauder + écran tactile. Outil portable de pentesting sans fil.",
      context: "Projet de découverte du pentesting sans fil sur matériel embarqué. L'ESP32 est relié à une antenne externe et un écran tactile, permettant une interaction directe avec le firmware. Utilisé uniquement dans un cadre éducatif et légal.",
      features: [
        "Scan des réseaux Wi-Fi & appareils Bluetooth à proximité",
        "Sniffing Wi-Fi (beacons, probes, trafic)",
        "Sniffing Bluetooth",
        "Fonctions offensives de test (Wi-Fi Killer, BT Killer, spam…)",
        "Interface tactile embarquée pour navigation dans les menus",
        "Outil portable, autonome, rapide à déployer",
        "Antenne externe pour portée étendue",
      ],
      tech: ["ESP32", "Firmware Marauder", "Wi-Fi", "Bluetooth", "Hardware embarqué", "Écran tactile"],
    },
    en: {
      title: "ESP32 Marauder — Wi-Fi & Bluetooth Pentesting",
      short: "ESP32 flashed with Marauder firmware + touchscreen. Portable wireless pentesting tool.",
      context: "A wireless pentesting discovery project on embedded hardware. The ESP32 is connected to an external antenna and touchscreen, enabling direct interaction with the firmware. Used only in an educational and legal context.",
      features: [
        "Scan nearby Wi-Fi networks & Bluetooth devices",
        "Wi-Fi sniffing (beacons, probes, traffic)",
        "Bluetooth sniffing",
        "Offensive test functions (Wi-Fi Killer, BT Killer, spam…)",
        "Embedded touchscreen for menu navigation",
        "Portable, autonomous, quick to deploy",
        "External antenna for extended range",
      ],
      tech: ["ESP32", "Marauder Firmware", "Wi-Fi", "Bluetooth", "Embedded Hardware", "Touchscreen"],
    }
  },
  {
    id: "mdp",
    num: "003",
    github: "https://github.com/VictorFrr",
    demo: null,
    image: "images/mdp.svg",
    color: "#22d3ee",
    fr: {
      title: "Gestionnaire de mots de passe chiffré",
      short: "Application Python 100% locale avec interface graphique. Coffre-fort chiffré par mot de passe maître.",
      context: "Solution personnelle de gestion des mots de passe fonctionnant entièrement en local. Aucun serveur, aucune donnée transmise sur le réseau. Conçue pour être simple, sécurisée et maîtrisée de bout en bout.",
      features: [
        "Coffre-fort protégé par mot de passe maître",
        "Données chiffrées localement (aucun envoi réseau)",
        "Interface graphique propre avec Custom Tkinter",
        "Générateur de mots de passe sécurisé intégré",
        "Ajout, consultation et gestion des identifiants",
        "Application autonome utilisable hors ligne",
        "Séparation claire entre logique sécurité et UI",
      ],
      tech: ["Python", "Custom Tkinter", "Chiffrement local", "Stockage sécurisé"],
    },
    en: {
      title: "Local Encrypted Password Manager",
      short: "100% local Python app with GUI. Encrypted vault protected by a master password.",
      context: "A personal password management solution that runs entirely locally. No server, no network transmission. Designed to be simple, secure, and fully controlled end-to-end.",
      features: [
        "Vault protected by master password",
        "Locally encrypted data (no network transmission)",
        "Clean GUI with Custom Tkinter",
        "Built-in secure password generator",
        "Add, view and manage credentials",
        "Standalone app, works offline",
        "Clear separation between security logic and UI",
      ],
      tech: ["Python", "Custom Tkinter", "Local Encryption", "Secure Storage"],
    }
  },
  {
    id: "serveur",
    num: "004",
    github: "https://github.com/VictorFrr",
    demo: null,
    image: "images/serveur.svg",
    color: "#a3e635",
    fr: {
      title: "Serveur local auto-hébergé — Matériel recyclé",
      short: "Serveur Debian monté pour ~25€ avec du matériel récupéré lors d'un stage chez Dell.",
      context: "Création d'un serveur local à partir d'une ancienne tour et de disques durs récupérés lors d'un stage chez Dell. Objectif : apprendre l'administration système Linux et expérimenter l'auto-hébergement à très faible coût (~25€ de pièces complémentaires).",
      features: [
        "Réutilisation de matériel informatique recyclé",
        "Installation et configuration de Debian",
        "Administration et accès à distance",
        "Hébergement d'un serveur web pour tests",
        "Vérification de stabilité et de fonctionnement",
        "Système évolutif (RAID, sécurité, nouveaux services prévus)",
      ],
      tech: ["Debian / Linux", "Administration système", "Serveur web", "Hardware recyclé", "Réseau local"],
    },
    en: {
      title: "Self-hosted Local Server — Recycled Hardware",
      short: "Debian server built for ~€25 with hardware recovered during an internship at Dell.",
      context: "A local server built from an old tower and hard drives recovered during an internship at Dell. Goal: learn Linux system administration and experiment with self-hosting at very low cost (~€25 in additional parts).",
      features: [
        "Reuse of recycled computer hardware",
        "Installation and configuration of Debian",
        "Remote administration and access",
        "Web server hosting for testing",
        "Stability and operational verification",
        "Scalable system (RAID, security, new services planned)",
      ],
      tech: ["Debian / Linux", "System Administration", "Web Server", "Recycled Hardware", "Local Network"],
    }
  },
  {
    id: "keylogger",
    num: "005",
    github: "https://github.com/VictorFrr",
    demo: null,
    image: "images/keylogger.svg",
    color: "#f97316",
    fr: {
      title: "Keylogger pédagogique — Pentest & Sensibilisation",
      short: "Module Python développé avec un camarade. Comprendre les logiciels espions pour mieux s'en défendre.",
      context: "Module avancé intégré dans le tool principal de cybersécurité. Développé en collaboration avec un camarade dans un cadre éducatif strict : tests uniquement sur machines autorisées, personnes informées et consentantes. Objectif : comprendre les mécanismes des logiciels espions pour mieux les détecter et contrer.",
      features: [
        "Capture périodique de screenshots",
        "Envoi automatisé via bot Discord (canal privé de test)",
        "Récupération du contenu du presse-papier",
        "Persistance au redémarrage (test de vecteur)",
        "Détection de motifs sensibles (emails, etc.)",
        "Interface graphique Custom Tkinter pour la configuration",
        "Module isolé et documenté comme outil de sensibilisation",
      ],
      tech: ["Python", "Custom Tkinter", "Bot Discord", "Pentest pédagogique"],
    },
    en: {
      title: "Educational Keylogger — Pentest & Awareness",
      short: "Python module developed with a classmate. Understand spyware to better defend against it.",
      context: "Advanced module integrated into the main cybersecurity tool. Developed collaboratively in a strict educational context: tests only on authorized machines, informed and consenting subjects. Goal: understand spyware mechanisms to better detect and counter them.",
      features: [
        "Periodic screenshot capture",
        "Automated sending via Discord bot (private test channel)",
        "Clipboard content retrieval",
        "Reboot persistence (vector test)",
        "Sensitive pattern detection (emails, etc.)",
        "Custom Tkinter GUI for configuration",
        "Isolated module documented as an awareness tool",
      ],
      tech: ["Python", "Custom Tkinter", "Discord Bot", "Educational Pentesting"],
    }
  },
  {
    id: "vba",
    num: "006",
    github: "https://github.com/VictorFrr",
    demo: null,
    image: "images/vba.svg",
    color: "#4ade80",
    fr: {
      title: "Outil VBA — Fusion & Nettoyage Excel",
      short: "Macro Excel automatisant la fusion de fichiers, le nettoyage des données et la génération d'un journal.",
      context: "Outil développé pour automatiser un traitement manuel répétitif et sujet aux erreurs. Remplace une manipulation manuelle longue par un processus simple, reproductible et traçable, utilisable directement depuis Excel.",
      features: [
        "Fusion automatique de plusieurs fichiers Excel",
        "Nettoyage des lignes vides et données inutiles",
        "Renumérotation automatique des lignes",
        "Journal d'import horodaté",
        "Aucune dépendance externe — fonctionne dans Excel",
        "Interface simple pour l'utilisateur final",
      ],
      tech: ["VBA", "Microsoft Excel", "Automatisation bureautique", "Macros"],
    },
    en: {
      title: "VBA Tool — Excel Merge & Cleanup",
      short: "Excel macro automating file merging, data cleanup and journal generation.",
      context: "A tool developed to automate a repetitive, error-prone manual process. Replaces long manual manipulation with a simple, reproducible, and traceable process, usable directly from Excel.",
      features: [
        "Automatic merging of multiple Excel files",
        "Cleanup of blank rows and unnecessary data",
        "Automatic row renumbering",
        "Timestamped import journal",
        "No external dependencies — runs inside Excel",
        "Simple interface for the end user",
      ],
      tech: ["VBA", "Microsoft Excel", "Office Automation", "Macros"],
    }
  },
  {
    id: "pc",
    num: "007",
    github: "https://github.com/VictorFrr",
    demo: null,
    image: "images/pc.svg",
    color: "#e879f9",
    fr: {
      title: "Montage PC Custom — De A à Z",
      short: "Assemblage complet d'un PC fixe : Ryzen 5 5600X, RTX 4060, 32 Go DDR4. Fait seul, de A à Z.",
      context: "Projet personnel consistant à choisir, acheter et assembler entièrement un PC fixe performant. Objectif : comprendre concrètement le fonctionnement interne d'un ordinateur et être capable de monter, diagnostiquer et faire évoluer une machine sans assistance.",
      features: [
        "CPU : AMD Ryzen 5 5600X",
        "GPU : NVIDIA RTX 4060",
        "RAM : 32 Go DDR4 3200 MHz Corsair",
        "Stockage : SSD 500 Go + HDD 4 To",
        "Alimentation : 650W",
        "Câblage interne propre et organisé",
        "Tests de stabilité et de performances",
        "Installation et configuration du système",
      ],
      tech: ["AMD Ryzen 5 5600X", "NVIDIA RTX 4060", "DDR4 32 Go", "Hardware", "Assemblage PC"],
    },
    en: {
      title: "Custom PC Build — Start to Finish",
      short: "Full PC build: Ryzen 5 5600X, RTX 4060, 32GB DDR4. Done solo, start to finish.",
      context: "A personal project involving selecting, purchasing and fully assembling a high-performance desktop PC. Goal: concretely understand the internal workings of a computer and be able to build, diagnose and upgrade a machine without assistance.",
      features: [
        "CPU: AMD Ryzen 5 5600X",
        "GPU: NVIDIA RTX 4060",
        "RAM: 32GB DDR4 3200MHz Corsair",
        "Storage: 500GB SSD + 4TB HDD",
        "PSU: 650W",
        "Clean and organized internal cable management",
        "Stability and performance testing",
        "OS installation and configuration",
      ],
      tech: ["AMD Ryzen 5 5600X", "NVIDIA RTX 4060", "32GB DDR4", "Hardware", "PC Assembly"],
    }
  },
  {
    id: "arcade",
    num: "008",
    github: "https://github.com/VictorFrr",
    demo: null,
    image: "images/arcade.svg",
    color: "#f97316",
    fr: {
      title: "Borne d'arcade custom — De A à Z",
      short: "Borne d'arcade complète construite à la main : Raspberry Pi 4, RetroPie, centaines de ROMs, écran Dell récupéré, structure en bois faite maison.",
      context: "Construction intégrale d'une borne d'arcade 100% fonctionnelle. Tout a été fait à la main : la structure en bois (découpe, ponçage, vissage), le câblage électronique, la configuration logicielle et l'intégration du kit joystick/boutons. L'écran provient d'un Dell que l'entreprise allait jeter — récupéré et réutilisé.",
      features: [
        "Raspberry Pi 4 (8 Go RAM) comme cerveau de la borne",
        "RetroPie flashé et configuré — OS dédié au rétrogaming",
        "Centaines de ROMs sur ~15 consoles différentes (NES, SNES, PS1, GBA…)",
        "Écran Dell récupéré et intégré dans la structure",
        "Kit joystick + boutons arcade câblé et configuré",
        "Structure entière construite en bois (découpe, ponçage, vissage, assemblage)",
        "Borne 100% fonctionnelle et autonome",
      ],
      tech: ["Raspberry Pi 4", "RetroPie", "Linux embarqué", "Électronique", "Bois / Fabrication", "ROMs"],
    },
    en: {
      title: "Custom Arcade Cabinet — Start to Finish",
      short: "Full arcade cabinet built by hand: Raspberry Pi 4, RetroPie, hundreds of ROMs, salvaged Dell screen, homemade wooden structure.",
      context: "Complete build of a 100% functional arcade cabinet. Everything was handmade: the wooden structure (cutting, sanding, screwing), electronics wiring, software configuration and joystick/button kit integration. The screen was salvaged from a Dell unit that was about to be thrown away.",
      features: [
        "Raspberry Pi 4 (8GB RAM) as the brain of the cabinet",
        "RetroPie flashed and configured — dedicated retrogaming OS",
        "Hundreds of ROMs across ~15 different consoles (NES, SNES, PS1, GBA…)",
        "Salvaged Dell screen integrated into the structure",
        "Arcade joystick + button kit wired and configured",
        "Full wooden structure built from scratch (cutting, sanding, screwing, assembly)",
        "100% functional and standalone cabinet",
      ],
      tech: ["Raspberry Pi 4", "RetroPie", "Embedded Linux", "Electronics", "Wood / Fabrication", "ROMs"],
    }
  },
  {
    id: "streamdeck",
    num: "009",
    github: "https://github.com/VictorFrr",
    demo: null,
    image: "images/streamdeck.svg",
    color: "#22d3ee",
    fr: {
      title: "Contrôleur audio Bluetooth — Stream Deck DIY",
      short: "ESP32 + potentiomètres en Bluetooth pour contrôler le volume de chaque application (Discord, CSGO, Steam, Apple Music…) depuis un boîtier physique.",
      context: "Création d'un contrôleur audio physique maison, similaire à un Stream Deck, permettant de régler le volume de chaque application indépendamment depuis des potentiomètres. L'ESP32 envoie les valeurs en Bluetooth au PC, un script Python tourne en arrière-plan et ajuste les volumes en temps réel. Le script se lance automatiquement au démarrage du PC via le dossier Démarrage Windows.",
      features: [
        "ESP32 relié en Bluetooth au PC",
        "Potentiomètres physiques — un par application",
        "Contrôle indépendant : Apple Music, Discord, CS:GO, Steam, Volume général",
        "Script Python en arrière-plan qui reçoit les valeurs BT et ajuste les volumes",
        "Démarrage automatique au lancement du PC (dossier Startup Windows)",
        "Script embarqué sur l'ESP32 pour lecture des potentiomètres et envoi BT",
        "Boîtier physique entièrement fonctionnel",
      ],
      tech: ["ESP32", "Bluetooth", "Python", "Script embarqué", "Windows API", "Électronique"],
    },
    en: {
      title: "Bluetooth Audio Controller — DIY Stream Deck",
      short: "ESP32 + potentiometers over Bluetooth to control volume per app (Discord, CSGO, Steam, Apple Music…) from a physical device.",
      context: "A homemade physical audio controller, similar to a Stream Deck, allowing independent volume control per application using potentiometers. The ESP32 sends values over Bluetooth to the PC, a Python script runs in the background and adjusts volumes in real time. The script auto-starts on Windows boot via the Startup folder.",
      features: [
        "ESP32 connected via Bluetooth to the PC",
        "Physical potentiometers — one per application",
        "Independent control: Apple Music, Discord, CS:GO, Steam, Master volume",
        "Python background script receiving BT values and adjusting volumes",
        "Auto-start on PC boot (Windows Startup folder)",
        "Firmware on ESP32 for potentiometer reading and BT transmission",
        "Fully functional physical enclosure",
      ],
      tech: ["ESP32", "Bluetooth", "Python", "Embedded Firmware", "Windows API", "Electronics"],
    }
  },
  {
    id: "sites",
    num: "010",
    github: "https://github.com/VictorFrr",
    demo: null,
    image: "images/sites.svg",
    color: "#a78bfa",
    fr: {
      title: "Sites web — Portfolios & Site entreprise",
      short: "Plusieurs sites web réalisés en HTML, CSS, JS : portfolios personnels, site pour l'entreprise TMI Orion (entreprise familiale), apprentissage via stage et formation JS.",
      context: "Réalisation de nombreux projets web en HTML, CSS et JavaScript pur. Parmi eux : plusieurs versions de portfolios personnels (dont ce site), et un site vitrine pour l'entreprise familiale TMI Orion. Ces projets ont été développés grâce aux compétences acquises en Bac Pro CIEL et lors d'un stage où une formation JavaScript a été suivie.",
      features: [
        "Plusieurs portfolios personnels — itérations et améliorations progressives",
        "Site vitrine pour TMI Orion (entreprise de famille)",
        "100% HTML, CSS, JavaScript vanilla — aucun framework",
        "Formation JavaScript suivie en stage — mise en pratique immédiate",
        "Responsive design, animations CSS, interactions JS",
        "Déploiement sur Vercel",
        "Apprentissage continu du développement web front-end",
      ],
      tech: ["HTML", "CSS", "JavaScript", "Vercel", "Responsive Design", "Animations CSS"],
    },
    en: {
      title: "Web Projects — Portfolios & Business Website",
      short: "Multiple websites in HTML, CSS, JS: personal portfolios, business site for TMI Orion (family company), skills built through internship and JS training.",
      context: "Several web projects built in pure HTML, CSS and JavaScript. Among them: multiple versions of personal portfolios (including this site) and a showcase website for the family business TMI Orion. These projects were developed using skills acquired in Bac Pro CIEL and during an internship that included a JavaScript training course.",
      features: [
        "Multiple personal portfolios — iterative improvements over time",
        "Showcase website for TMI Orion (family business)",
        "100% HTML, CSS, vanilla JavaScript — no framework",
        "JavaScript training during internship — immediately applied",
        "Responsive design, CSS animations, JS interactions",
        "Deployed on Vercel",
        "Continuous front-end web development learning",
      ],
      tech: ["HTML", "CSS", "JavaScript", "Vercel", "Responsive Design", "CSS Animations"],
    }
  },
];

// Patch: add stats + availability to translations
(function() {
  TRANSLATIONS.fr.stats = { projects: "Projets réalisés", langs: "Langages maîtrisés", years: "Ans d'expérience", consoles: "Consoles émulées" };
  TRANSLATIONS.en.stats = { projects: "Projects built", langs: "Languages mastered", years: "Years experience", consoles: "Consoles emulated" };
  TRANSLATIONS.fr.contact.available = "Disponible pour stage / alternance";
  TRANSLATIONS.en.contact.available = "Available for internship / apprenticeship";
})();
